// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Vektor',
      items: [
        {
          type: 'category',
          label: 'Documentación de Usuario',
          items: [
            {
              type: 'autogenerated',
              dirName: 'vektor/usuario',
            },
          ],
        },
        {
          type: 'category',
          label: 'Documentación Técnica',
          items: [
            {
              type: 'category',
              label: 'FrontEnd',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'vektor/tecnica/FrontEnd',
                },
              ],
            },
            {
              type: 'category',
              label: 'BackEnd',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'vektor/tecnica/BackEnd',
                },
              ],
            },
            {
              type: 'category',
              label: 'Modulos',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'vektor/tecnica/Modulos',
                },
              ],
            },
            {
              type: 'category',
              label: 'Arquitectura',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'vektor/tecnica/Arquitectura',
                },
              ],
            },
          ],
        }
      ],
    }
  ],

};

export default sidebars;
